/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";
import type {
  ChargeListResponse,
  ChargeRequest,
  ChargeResponse,
  GetChargesParams,
} from "../documentation.schemas";

export const getCharges = <TData = AxiosResponse<ChargeListResponse>>(
  params?: GetChargesParams,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.get(`/charges`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
export const postCharges = <TData = AxiosResponse<ChargeResponse>>(
  chargeRequest: ChargeRequest,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.post(`/charges`, chargeRequest, options);
};
export const getChargesId = <TData = AxiosResponse<ChargeResponse>>(
  id: number,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.get(`/charges/${id}`, options);
};
export const putChargesId = <TData = AxiosResponse<ChargeResponse>>(
  id: number,
  chargeRequest: ChargeRequest,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.put(`/charges/${id}`, chargeRequest, options);
};
export const deleteChargesId = <TData = AxiosResponse<number>>(
  id: number,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.delete(`/charges/${id}`, options);
};
export type GetChargesResult = AxiosResponse<ChargeListResponse>;
export type PostChargesResult = AxiosResponse<ChargeResponse>;
export type GetChargesIdResult = AxiosResponse<ChargeResponse>;
export type PutChargesIdResult = AxiosResponse<ChargeResponse>;
export type DeleteChargesIdResult = AxiosResponse<number>;
