/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * DOCUMENTATION
 * OpenAPI spec version: 1.0.0
 */
export type GetChargesParams = {
  /**
   * Sort by attributes ascending (asc) or descending (desc)
   */
  sort?: string;
  /**
   * Return page/pageSize (default: true)
   */
  "pagination[withCount]"?: boolean;
  /**
   * Page number (default: 0)
   */
  "pagination[page]"?: number;
  /**
   * Page size (default: 25)
   */
  "pagination[pageSize]"?: number;
  /**
   * Offset value (default: 0)
   */
  "pagination[start]"?: number;
  /**
   * Number of entities to return (default: 25)
   */
  "pagination[limit]"?: number;
  /**
   * Fields to return (ex: title,author)
   */
  fields?: string;
  /**
   * Relations to return
   */
  populate?: string;
  /**
   * Filters to apply
   */
  filters?: { [key: string]: any };
  /**
   * Locale to apply
   */
  locale?: string;
};

export type ChargeResponseMeta = { [key: string]: any };

export interface ChargeResponse {
  data?: ChargeResponseDataObject;
  meta?: ChargeResponseMeta;
}

export interface Charge {
  added_by?: string;
  amount?: number;
  card_type?: ChargeCardType;
  createdAt?: string;
  createdBy?: ChargeCreatedBy;
  date?: string;
  description?: string;
  publishedAt?: string;
  updatedAt?: string;
  updatedBy?: ChargeUpdatedBy;
}

export interface ChargeResponseDataObject {
  attributes?: Charge;
  id?: number;
}

export type ChargeUpdatedByDataAttributes = { [key: string]: any };

export type ChargeUpdatedByData = {
  attributes?: ChargeUpdatedByDataAttributes;
  id?: number;
};

export type ChargeUpdatedBy = {
  data?: ChargeUpdatedByData;
};

export type ChargeCreatedByData = {
  attributes?: ChargeCreatedByDataAttributes;
  id?: number;
};

export type ChargeCreatedBy = {
  data?: ChargeCreatedByData;
};

export type ChargeCreatedByDataAttributesUpdatedByDataAttributes = {
  [key: string]: any;
};

export type ChargeCreatedByDataAttributesUpdatedByData = {
  attributes?: ChargeCreatedByDataAttributesUpdatedByDataAttributes;
  id?: number;
};

export type ChargeCreatedByDataAttributesUpdatedBy = {
  data?: ChargeCreatedByDataAttributesUpdatedByData;
};

export type ChargeCreatedByDataAttributesRolesDataItem = {
  attributes?: ChargeCreatedByDataAttributesRolesDataItemAttributes;
  id?: number;
};

export type ChargeCreatedByDataAttributesRoles = {
  data?: ChargeCreatedByDataAttributesRolesDataItem[];
};

export type ChargeCreatedByDataAttributes = {
  blocked?: boolean;
  createdAt?: string;
  createdBy?: ChargeCreatedByDataAttributesCreatedBy;
  email?: string;
  firstname?: string;
  isActive?: boolean;
  lastname?: string;
  preferedLanguage?: string;
  registrationToken?: string;
  resetPasswordToken?: string;
  roles?: ChargeCreatedByDataAttributesRoles;
  updatedAt?: string;
  updatedBy?: ChargeCreatedByDataAttributesUpdatedBy;
  username?: string;
};

export type ChargeCreatedByDataAttributesRolesDataItemAttributesUsersDataItemAttributes =
  { [key: string]: any };

export type ChargeCreatedByDataAttributesRolesDataItemAttributesUsersDataItem =
  {
    attributes?: ChargeCreatedByDataAttributesRolesDataItemAttributesUsersDataItemAttributes;
    id?: number;
  };

export type ChargeCreatedByDataAttributesRolesDataItemAttributesUsers = {
  data?: ChargeCreatedByDataAttributesRolesDataItemAttributesUsersDataItem[];
};

export type ChargeCreatedByDataAttributesRolesDataItemAttributesUpdatedByDataAttributes =
  { [key: string]: any };

export type ChargeCreatedByDataAttributesRolesDataItemAttributesUpdatedByData =
  {
    attributes?: ChargeCreatedByDataAttributesRolesDataItemAttributesUpdatedByDataAttributes;
    id?: number;
  };

export type ChargeCreatedByDataAttributesRolesDataItemAttributesUpdatedBy = {
  data?: ChargeCreatedByDataAttributesRolesDataItemAttributesUpdatedByData;
};

export type ChargeCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItem =
  {
    attributes?: ChargeCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributes;
    id?: number;
  };

export type ChargeCreatedByDataAttributesRolesDataItemAttributesPermissions = {
  data?: ChargeCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItem[];
};

export type ChargeCreatedByDataAttributesRolesDataItemAttributes = {
  code?: string;
  createdAt?: string;
  createdBy?: ChargeCreatedByDataAttributesRolesDataItemAttributesCreatedBy;
  description?: string;
  name?: string;
  permissions?: ChargeCreatedByDataAttributesRolesDataItemAttributesPermissions;
  updatedAt?: string;
  updatedBy?: ChargeCreatedByDataAttributesRolesDataItemAttributesUpdatedBy;
  users?: ChargeCreatedByDataAttributesRolesDataItemAttributesUsers;
};

export type ChargeCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesUpdatedByDataAttributes =
  { [key: string]: any };

export type ChargeCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesUpdatedByData =
  {
    attributes?: ChargeCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesUpdatedByDataAttributes;
    id?: number;
  };

export type ChargeCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesUpdatedBy =
  {
    data?: ChargeCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesUpdatedByData;
  };

export type ChargeCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributes =
  {
    action?: string;
    actionParameters?: ChargeCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesActionParameters;
    conditions?: ChargeCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesConditions;
    createdAt?: string;
    createdBy?: ChargeCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesCreatedBy;
    properties?: ChargeCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesProperties;
    role?: ChargeCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesRole;
    subject?: string;
    updatedAt?: string;
    updatedBy?: ChargeCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesUpdatedBy;
  };

export type ChargeCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesRoleDataAttributes =
  { [key: string]: any };

export type ChargeCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesRoleData =
  {
    attributes?: ChargeCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesRoleDataAttributes;
    id?: number;
  };

export type ChargeCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesRole =
  {
    data?: ChargeCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesRoleData;
  };

export type ChargeCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesProperties =
  {};

export type ChargeCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesCreatedByDataAttributes =
  { [key: string]: any };

export type ChargeCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesCreatedByData =
  {
    attributes?: ChargeCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesCreatedByDataAttributes;
    id?: number;
  };

export type ChargeCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesCreatedBy =
  {
    data?: ChargeCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesCreatedByData;
  };

export type ChargeCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesConditions =
  {};

export type ChargeCreatedByDataAttributesRolesDataItemAttributesPermissionsDataItemAttributesActionParameters =
  {};

export type ChargeCreatedByDataAttributesRolesDataItemAttributesCreatedByDataAttributes =
  { [key: string]: any };

export type ChargeCreatedByDataAttributesRolesDataItemAttributesCreatedByData =
  {
    attributes?: ChargeCreatedByDataAttributesRolesDataItemAttributesCreatedByDataAttributes;
    id?: number;
  };

export type ChargeCreatedByDataAttributesRolesDataItemAttributesCreatedBy = {
  data?: ChargeCreatedByDataAttributesRolesDataItemAttributesCreatedByData;
};

export type ChargeCreatedByDataAttributesCreatedByDataAttributes = {
  [key: string]: any;
};

export type ChargeCreatedByDataAttributesCreatedByData = {
  attributes?: ChargeCreatedByDataAttributesCreatedByDataAttributes;
  id?: number;
};

export type ChargeCreatedByDataAttributesCreatedBy = {
  data?: ChargeCreatedByDataAttributesCreatedByData;
};

export type ChargeCardType =
  (typeof ChargeCardType)[keyof typeof ChargeCardType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChargeCardType = {
  amex: "amex",
  chase: "chase",
} as const;

export type ChargeListResponseMetaPagination = {
  page?: number;
  pageCount?: number;
  pageSize?: number;
  total?: number;
};

export type ChargeListResponseMeta = {
  pagination?: ChargeListResponseMetaPagination;
};

export interface ChargeListResponseDataItem {
  attributes?: Charge;
  id?: number;
}

export interface ChargeListResponse {
  data?: ChargeListResponseDataItem[];
  meta?: ChargeListResponseMeta;
}

export type ChargeRequestDataCardType =
  (typeof ChargeRequestDataCardType)[keyof typeof ChargeRequestDataCardType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChargeRequestDataCardType = {
  amex: "amex",
  chase: "chase",
} as const;

export type ChargeRequestData = {
  added_by?: string;
  amount?: number;
  card_type?: ChargeRequestDataCardType;
  date?: string;
  description?: string;
};

export interface ChargeRequest {
  data: ChargeRequestData;
}

export type ErrorErrorDetails = { [key: string]: any };

export type ErrorError = {
  details?: ErrorErrorDetails;
  message?: string;
  name?: string;
  status?: number;
};

export interface Error {
  data?: ErrorData;
  error: ErrorError;
}

export type ErrorDataOneOfTwoItem = { [key: string]: any };

export type ErrorDataOneOf = { [key: string]: any };

export type ErrorData = ErrorDataOneOf | ErrorDataOneOfTwoItem[] | null;
